---
title: 'BGmisc: An R Package for Behavior Genetics Analysis'
output:
  rmarkdown::html_vignette:
    keep_md: TRUE
tags:
  - R
  - pedigrees
  - behavior genetics
authors:
  - name: S. Mason Garrison
    orcid: 0000-0000-0000-0000
    affiliation: 1
  - name: Michael D. Hunter
    orcid: 0000-0002-3651-6709
    affiliation: 2
  - name: Xuanyu Lyu
    orcid: 0000-0000-0000-0000
    affiliation: 1
  - name: Jonathan D. Trattner
    orcid: 0000-0000-0000-0000
    affiliation: 3  
  - name: S. Alexandra Burt
    orcid: 0000-0000-0000-0000
    affiliation: 4
affiliations:
 - name: University, Place, USA
   index: 1
 - name: University, Place, USA
   index: 2
 - name: University, Place, USA
   index: 3
 - name: University, Place, USA
   index: 4
date: 07/21/2023
bibliography: paper.bib
vignette: >
  %\VignetteEncoding{UTF-8}
  %\VignetteIndexEntry{BGmisc: An R Package for Behavior Genetics Analysis}
  %\VignetteEngine{knitr::rmarkdown}
---
<!--Guidance 
JOSS welcomes submissions from broadly diverse research areas. For this reason, we require that authors include in the paper some sentences that explain the software functionality and domain of use to a non-specialist reader. We also require that authors explain the research applications of the software. The paper should be between 250-1000 words. Authors submitting papers significantly longer than 1000 words may be asked to reduce the length of their paper.
Your paper should include:

A list of the authors of the software and their affiliations, using the correct format (see the example below).
A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience.
A Statement of need section that clearly illustrates the research purpose of the software and places it in the context of related work.
A list of key references, including to other software addressing related needs. Note that the references should include full names of venues, e.g., journals and conferences, not abbreviations only understood in the context of a specific discipline.
Mention (if applicable) a representative set of past or ongoing research projects using the software and recent scholarly publications enabled by it.
Acknowledgment of any financial support.
-->
# Summary
<!-- > A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience. -->

The field of behavior genetics seeks to understand the genetic and environmental influences on individual differences in behavior. As research in this domain has expanded beyond classical twin studies, so has the need for specialized tools to facilitate complex analyses. The BGmisc package addresses this need by offering a suite of functions tailored for behavior genetic modeling and complex data structures.

## Features

- Provides behavior genetic miscellaneous functions for modeling and analysis.
- Calculates the relatedness coefficient between two individuals based on their shared ancestry, using path tracing rules first described in [@Wright1922].
- Infers the relatedness between two individuals based on the observed correlation between their additive genetic variance and shared environmental variance.
- Determines if a variance components model is identified and fits the estimated variance components of a model to covariance data.
- Converts a pedigree into various types of relatedness matrices, including additive genetics, mitochondrial, common nuclear, and extended environmental relatedness matrices.
- Simulates pedigrees based on parameters like the number of children per couple, the number of generations, the sex ratio of offspring, and birth rate. 



# Statement of need

`BGmisc` is an R package for extended family data, such as pedigrees. It contains a variety of behavior genetic functions. It was designed to [do what it does]. It [describe the dependencies and compatibilities].


`BGmisc` was designed to be used by behavior geneticists and others working with large pedigree data. It was developed as part of a grant, and has been used in several projects (e.g., ) and theses (cite xuanyu). Further, the technical aspects related to model identification have been described in Hunter et al. [@hunter_analytic_2021].


The study of intricate family structures, beyond classic twins, requires specialized tools to model genetic relationships, infer relatedness, simulate pedigrees, and convert pedigrees into various relatedness matrices. BGmisc meets this need by offering a comprehensive suite of functions designed specifically for these complex analyses:

The BGmisc package is designed to accommodate the intricate relationships found in extended family structures, moving beyond the limitations of classic twin studies. Its features include:

- Relatedness Coefficient Calculation: Utilizing path tracing rules, BGmisc calculates the relatedness coefficient between individuals in complex family structures, reflecting the multifaceted nature of extended family relationships.

- Relatedness Inference: The package infers the relatedness between individuals in extended family structures by correlating their additive genetic variance and shared environmental variance.

- Model Identification: BGmisc determines if a variance components model is identified and fits the estimated variance components of a model to covariance data.

- Pedigree Conversion: The package converts pedigrees into various relatedness matrices, including additive genetics, mitochondrial, common nuclear, and extended environmental relatedness matrices, catering to the diverse needs of non-twin family structures.

- Pedigree Simulation: BGmisc simulates pedigrees based on parameters like the number of children per couple, generations, sex ratio, and birth rate, allowing for the modeling of intricate family dynamics beyond classic twins.

These features collectively enable researchers and practitioners to conduct more nuanced analyses of genetic relationships, facilitating the exploration of the multifaceted genetic relationships that shape human behavior.


# Availability

The BGmisc package is open-source and available on both GitHub at https://github.com/R-Computing-Lab/BGmisc and the Comprehensive R Archive Network (CRAN)  at https://cran.r-project.org/package=BGmisc. It is licensed under the GNU General Public License


# Acknowledgements

The current research is supported by the National Institute on Aging (NIA), RF1-AG073189. We would like to acknowledge assistance from Carlos Santos.


# References
